#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : shim
Version  : 15
Release  : 17
URL      : https://github.com/rhboot/shim/releases/download/15/shim-15.tar.bz2
Source0  : https://github.com/rhboot/shim/releases/download/15/shim-15.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: shim-license = %{version}-%{release}
BuildRequires : gnu-efi
BuildRequires : gnu-efi-dev
BuildRequires : nss-bin
BuildRequires : openssl-dev
BuildRequires : pesign
BuildRequires : util-linux
Patch1: 0001-Add-Intel-Certificate.patch

%description
shim is a trivial EFI application that, when run, attempts to open and
execute another application. It will initially attempt to do this via the
standard EFI LoadImage() and StartImage() calls. If these fail (because secure
boot is enabled and the binary is not signed with an appropriate key, for
instance) it will then validate the binary against a built-in certificate. If
this succeeds and if the binary or signing key are not blacklisted then shim
will relocate and execute the binary.

%package license
Summary: license components for the shim package.
Group: Default

%description license
license components for the shim package.


%prep
%setup -q -n shim-15
%patch1 -p1

%build
## build_prepend content
openssl x509 -in clear-linux-sb.pem -out clear-linux-sb.cer -outform der
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542433477
make  %{?_smp_mflags} EFI_CRT_OBJS=/usr/lib64/crt0-efi-x86_64.o DEFAULT_LOADER=loaderx64.efi VENDOR_CERT_FILE=clear-linux-sb.cer OVERRIDE_SECURITY_POLICY=1

%install
export SOURCE_DATE_EPOCH=1542433477
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/shim
cp COPYRIGHT %{buildroot}/usr/share/package-licenses/shim/COPYRIGHT
true
## install_append content
mkdir -p %{buildroot}/usr/lib/shim
/usr/bin/install -p -D -m 0755 shimx64.efi %{buildroot}/usr/lib/shim/shimx64.efi
/usr/bin/install -p -D -m 0755 mmx64.efi %{buildroot}/usr/lib/shim/mmx64.efi
/usr/bin/install -p -D -m 0755 fbx64.efi %{buildroot}/usr/lib/shim/fbx64.efi
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/shim/fbx64.efi
/usr/lib/shim/mmx64.efi
/usr/lib/shim/shimx64.efi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/shim/COPYRIGHT
